/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package velibstreaming.avro.record.source;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroStationAvailability extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1588865257962812688L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroStationAvailability\",\"namespace\":\"velibstreaming.avro.record.source\",\"fields\":[{\"name\":\"stationCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"mechanicalBikesAtStation\",\"type\":\"int\"},{\"name\":\"electricBikesAtStation\",\"type\":\"int\"},{\"name\":\"availabilityTimestamp\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"loadTimestamp\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"stationCapacity\",\"type\":\"int\"},{\"name\":\"stationName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"isRenting\",\"type\":\"boolean\"},{\"name\":\"isReturning\",\"type\":\"boolean\"},{\"name\":\"isInstalled\",\"type\":\"boolean\"},{\"name\":\"latitude\",\"type\":\"double\"},{\"name\":\"longitude\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroStationAvailability> ENCODER =
      new BinaryMessageEncoder<AvroStationAvailability>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroStationAvailability> DECODER =
      new BinaryMessageDecoder<AvroStationAvailability>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroStationAvailability> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroStationAvailability> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroStationAvailability> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroStationAvailability>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroStationAvailability to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroStationAvailability from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroStationAvailability instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroStationAvailability fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String stationCode;
  @Deprecated public int mechanicalBikesAtStation;
  @Deprecated public int electricBikesAtStation;
  @Deprecated public long availabilityTimestamp;
  @Deprecated public long loadTimestamp;
  @Deprecated public int stationCapacity;
  @Deprecated public java.lang.String stationName;
  @Deprecated public boolean isRenting;
  @Deprecated public boolean isReturning;
  @Deprecated public boolean isInstalled;
  @Deprecated public double latitude;
  @Deprecated public double longitude;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroStationAvailability() {}

  /**
   * All-args constructor.
   * @param stationCode The new value for stationCode
   * @param mechanicalBikesAtStation The new value for mechanicalBikesAtStation
   * @param electricBikesAtStation The new value for electricBikesAtStation
   * @param availabilityTimestamp The new value for availabilityTimestamp
   * @param loadTimestamp The new value for loadTimestamp
   * @param stationCapacity The new value for stationCapacity
   * @param stationName The new value for stationName
   * @param isRenting The new value for isRenting
   * @param isReturning The new value for isReturning
   * @param isInstalled The new value for isInstalled
   * @param latitude The new value for latitude
   * @param longitude The new value for longitude
   */
  public AvroStationAvailability(java.lang.String stationCode, java.lang.Integer mechanicalBikesAtStation, java.lang.Integer electricBikesAtStation, java.lang.Long availabilityTimestamp, java.lang.Long loadTimestamp, java.lang.Integer stationCapacity, java.lang.String stationName, java.lang.Boolean isRenting, java.lang.Boolean isReturning, java.lang.Boolean isInstalled, java.lang.Double latitude, java.lang.Double longitude) {
    this.stationCode = stationCode;
    this.mechanicalBikesAtStation = mechanicalBikesAtStation;
    this.electricBikesAtStation = electricBikesAtStation;
    this.availabilityTimestamp = availabilityTimestamp;
    this.loadTimestamp = loadTimestamp;
    this.stationCapacity = stationCapacity;
    this.stationName = stationName;
    this.isRenting = isRenting;
    this.isReturning = isReturning;
    this.isInstalled = isInstalled;
    this.latitude = latitude;
    this.longitude = longitude;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return stationCode;
    case 1: return mechanicalBikesAtStation;
    case 2: return electricBikesAtStation;
    case 3: return availabilityTimestamp;
    case 4: return loadTimestamp;
    case 5: return stationCapacity;
    case 6: return stationName;
    case 7: return isRenting;
    case 8: return isReturning;
    case 9: return isInstalled;
    case 10: return latitude;
    case 11: return longitude;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: stationCode = value$ != null ? value$.toString() : null; break;
    case 1: mechanicalBikesAtStation = (java.lang.Integer)value$; break;
    case 2: electricBikesAtStation = (java.lang.Integer)value$; break;
    case 3: availabilityTimestamp = (java.lang.Long)value$; break;
    case 4: loadTimestamp = (java.lang.Long)value$; break;
    case 5: stationCapacity = (java.lang.Integer)value$; break;
    case 6: stationName = value$ != null ? value$.toString() : null; break;
    case 7: isRenting = (java.lang.Boolean)value$; break;
    case 8: isReturning = (java.lang.Boolean)value$; break;
    case 9: isInstalled = (java.lang.Boolean)value$; break;
    case 10: latitude = (java.lang.Double)value$; break;
    case 11: longitude = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'stationCode' field.
   * @return The value of the 'stationCode' field.
   */
  public java.lang.String getStationCode() {
    return stationCode;
  }


  /**
   * Sets the value of the 'stationCode' field.
   * @param value the value to set.
   */
  public void setStationCode(java.lang.String value) {
    this.stationCode = value;
  }

  /**
   * Gets the value of the 'mechanicalBikesAtStation' field.
   * @return The value of the 'mechanicalBikesAtStation' field.
   */
  public int getMechanicalBikesAtStation() {
    return mechanicalBikesAtStation;
  }


  /**
   * Sets the value of the 'mechanicalBikesAtStation' field.
   * @param value the value to set.
   */
  public void setMechanicalBikesAtStation(int value) {
    this.mechanicalBikesAtStation = value;
  }

  /**
   * Gets the value of the 'electricBikesAtStation' field.
   * @return The value of the 'electricBikesAtStation' field.
   */
  public int getElectricBikesAtStation() {
    return electricBikesAtStation;
  }


  /**
   * Sets the value of the 'electricBikesAtStation' field.
   * @param value the value to set.
   */
  public void setElectricBikesAtStation(int value) {
    this.electricBikesAtStation = value;
  }

  /**
   * Gets the value of the 'availabilityTimestamp' field.
   * @return The value of the 'availabilityTimestamp' field.
   */
  public long getAvailabilityTimestamp() {
    return availabilityTimestamp;
  }


  /**
   * Sets the value of the 'availabilityTimestamp' field.
   * @param value the value to set.
   */
  public void setAvailabilityTimestamp(long value) {
    this.availabilityTimestamp = value;
  }

  /**
   * Gets the value of the 'loadTimestamp' field.
   * @return The value of the 'loadTimestamp' field.
   */
  public long getLoadTimestamp() {
    return loadTimestamp;
  }


  /**
   * Sets the value of the 'loadTimestamp' field.
   * @param value the value to set.
   */
  public void setLoadTimestamp(long value) {
    this.loadTimestamp = value;
  }

  /**
   * Gets the value of the 'stationCapacity' field.
   * @return The value of the 'stationCapacity' field.
   */
  public int getStationCapacity() {
    return stationCapacity;
  }


  /**
   * Sets the value of the 'stationCapacity' field.
   * @param value the value to set.
   */
  public void setStationCapacity(int value) {
    this.stationCapacity = value;
  }

  /**
   * Gets the value of the 'stationName' field.
   * @return The value of the 'stationName' field.
   */
  public java.lang.String getStationName() {
    return stationName;
  }


  /**
   * Sets the value of the 'stationName' field.
   * @param value the value to set.
   */
  public void setStationName(java.lang.String value) {
    this.stationName = value;
  }

  /**
   * Gets the value of the 'isRenting' field.
   * @return The value of the 'isRenting' field.
   */
  public boolean getIsRenting() {
    return isRenting;
  }


  /**
   * Sets the value of the 'isRenting' field.
   * @param value the value to set.
   */
  public void setIsRenting(boolean value) {
    this.isRenting = value;
  }

  /**
   * Gets the value of the 'isReturning' field.
   * @return The value of the 'isReturning' field.
   */
  public boolean getIsReturning() {
    return isReturning;
  }


  /**
   * Sets the value of the 'isReturning' field.
   * @param value the value to set.
   */
  public void setIsReturning(boolean value) {
    this.isReturning = value;
  }

  /**
   * Gets the value of the 'isInstalled' field.
   * @return The value of the 'isInstalled' field.
   */
  public boolean getIsInstalled() {
    return isInstalled;
  }


  /**
   * Sets the value of the 'isInstalled' field.
   * @param value the value to set.
   */
  public void setIsInstalled(boolean value) {
    this.isInstalled = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return The value of the 'latitude' field.
   */
  public double getLatitude() {
    return latitude;
  }


  /**
   * Sets the value of the 'latitude' field.
   * @param value the value to set.
   */
  public void setLatitude(double value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return The value of the 'longitude' field.
   */
  public double getLongitude() {
    return longitude;
  }


  /**
   * Sets the value of the 'longitude' field.
   * @param value the value to set.
   */
  public void setLongitude(double value) {
    this.longitude = value;
  }

  /**
   * Creates a new AvroStationAvailability RecordBuilder.
   * @return A new AvroStationAvailability RecordBuilder
   */
  public static velibstreaming.avro.record.source.AvroStationAvailability.Builder newBuilder() {
    return new velibstreaming.avro.record.source.AvroStationAvailability.Builder();
  }

  /**
   * Creates a new AvroStationAvailability RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroStationAvailability RecordBuilder
   */
  public static velibstreaming.avro.record.source.AvroStationAvailability.Builder newBuilder(velibstreaming.avro.record.source.AvroStationAvailability.Builder other) {
    if (other == null) {
      return new velibstreaming.avro.record.source.AvroStationAvailability.Builder();
    } else {
      return new velibstreaming.avro.record.source.AvroStationAvailability.Builder(other);
    }
  }

  /**
   * Creates a new AvroStationAvailability RecordBuilder by copying an existing AvroStationAvailability instance.
   * @param other The existing instance to copy.
   * @return A new AvroStationAvailability RecordBuilder
   */
  public static velibstreaming.avro.record.source.AvroStationAvailability.Builder newBuilder(velibstreaming.avro.record.source.AvroStationAvailability other) {
    if (other == null) {
      return new velibstreaming.avro.record.source.AvroStationAvailability.Builder();
    } else {
      return new velibstreaming.avro.record.source.AvroStationAvailability.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroStationAvailability instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroStationAvailability>
    implements org.apache.avro.data.RecordBuilder<AvroStationAvailability> {

    private java.lang.String stationCode;
    private int mechanicalBikesAtStation;
    private int electricBikesAtStation;
    private long availabilityTimestamp;
    private long loadTimestamp;
    private int stationCapacity;
    private java.lang.String stationName;
    private boolean isRenting;
    private boolean isReturning;
    private boolean isInstalled;
    private double latitude;
    private double longitude;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(velibstreaming.avro.record.source.AvroStationAvailability.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.stationCode)) {
        this.stationCode = data().deepCopy(fields()[0].schema(), other.stationCode);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.mechanicalBikesAtStation)) {
        this.mechanicalBikesAtStation = data().deepCopy(fields()[1].schema(), other.mechanicalBikesAtStation);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.electricBikesAtStation)) {
        this.electricBikesAtStation = data().deepCopy(fields()[2].schema(), other.electricBikesAtStation);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.availabilityTimestamp)) {
        this.availabilityTimestamp = data().deepCopy(fields()[3].schema(), other.availabilityTimestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.loadTimestamp)) {
        this.loadTimestamp = data().deepCopy(fields()[4].schema(), other.loadTimestamp);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.stationCapacity)) {
        this.stationCapacity = data().deepCopy(fields()[5].schema(), other.stationCapacity);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.stationName)) {
        this.stationName = data().deepCopy(fields()[6].schema(), other.stationName);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.isRenting)) {
        this.isRenting = data().deepCopy(fields()[7].schema(), other.isRenting);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.isReturning)) {
        this.isReturning = data().deepCopy(fields()[8].schema(), other.isReturning);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.isInstalled)) {
        this.isInstalled = data().deepCopy(fields()[9].schema(), other.isInstalled);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.latitude)) {
        this.latitude = data().deepCopy(fields()[10].schema(), other.latitude);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.longitude)) {
        this.longitude = data().deepCopy(fields()[11].schema(), other.longitude);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroStationAvailability instance
     * @param other The existing instance to copy.
     */
    private Builder(velibstreaming.avro.record.source.AvroStationAvailability other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.stationCode)) {
        this.stationCode = data().deepCopy(fields()[0].schema(), other.stationCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.mechanicalBikesAtStation)) {
        this.mechanicalBikesAtStation = data().deepCopy(fields()[1].schema(), other.mechanicalBikesAtStation);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.electricBikesAtStation)) {
        this.electricBikesAtStation = data().deepCopy(fields()[2].schema(), other.electricBikesAtStation);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.availabilityTimestamp)) {
        this.availabilityTimestamp = data().deepCopy(fields()[3].schema(), other.availabilityTimestamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.loadTimestamp)) {
        this.loadTimestamp = data().deepCopy(fields()[4].schema(), other.loadTimestamp);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.stationCapacity)) {
        this.stationCapacity = data().deepCopy(fields()[5].schema(), other.stationCapacity);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.stationName)) {
        this.stationName = data().deepCopy(fields()[6].schema(), other.stationName);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.isRenting)) {
        this.isRenting = data().deepCopy(fields()[7].schema(), other.isRenting);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.isReturning)) {
        this.isReturning = data().deepCopy(fields()[8].schema(), other.isReturning);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.isInstalled)) {
        this.isInstalled = data().deepCopy(fields()[9].schema(), other.isInstalled);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.latitude)) {
        this.latitude = data().deepCopy(fields()[10].schema(), other.latitude);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.longitude)) {
        this.longitude = data().deepCopy(fields()[11].schema(), other.longitude);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'stationCode' field.
      * @return The value.
      */
    public java.lang.String getStationCode() {
      return stationCode;
    }


    /**
      * Sets the value of the 'stationCode' field.
      * @param value The value of 'stationCode'.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder setStationCode(java.lang.String value) {
      validate(fields()[0], value);
      this.stationCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'stationCode' field has been set.
      * @return True if the 'stationCode' field has been set, false otherwise.
      */
    public boolean hasStationCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'stationCode' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder clearStationCode() {
      stationCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'mechanicalBikesAtStation' field.
      * @return The value.
      */
    public int getMechanicalBikesAtStation() {
      return mechanicalBikesAtStation;
    }


    /**
      * Sets the value of the 'mechanicalBikesAtStation' field.
      * @param value The value of 'mechanicalBikesAtStation'.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder setMechanicalBikesAtStation(int value) {
      validate(fields()[1], value);
      this.mechanicalBikesAtStation = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'mechanicalBikesAtStation' field has been set.
      * @return True if the 'mechanicalBikesAtStation' field has been set, false otherwise.
      */
    public boolean hasMechanicalBikesAtStation() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'mechanicalBikesAtStation' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder clearMechanicalBikesAtStation() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'electricBikesAtStation' field.
      * @return The value.
      */
    public int getElectricBikesAtStation() {
      return electricBikesAtStation;
    }


    /**
      * Sets the value of the 'electricBikesAtStation' field.
      * @param value The value of 'electricBikesAtStation'.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder setElectricBikesAtStation(int value) {
      validate(fields()[2], value);
      this.electricBikesAtStation = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'electricBikesAtStation' field has been set.
      * @return True if the 'electricBikesAtStation' field has been set, false otherwise.
      */
    public boolean hasElectricBikesAtStation() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'electricBikesAtStation' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder clearElectricBikesAtStation() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'availabilityTimestamp' field.
      * @return The value.
      */
    public long getAvailabilityTimestamp() {
      return availabilityTimestamp;
    }


    /**
      * Sets the value of the 'availabilityTimestamp' field.
      * @param value The value of 'availabilityTimestamp'.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder setAvailabilityTimestamp(long value) {
      validate(fields()[3], value);
      this.availabilityTimestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'availabilityTimestamp' field has been set.
      * @return True if the 'availabilityTimestamp' field has been set, false otherwise.
      */
    public boolean hasAvailabilityTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'availabilityTimestamp' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder clearAvailabilityTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'loadTimestamp' field.
      * @return The value.
      */
    public long getLoadTimestamp() {
      return loadTimestamp;
    }


    /**
      * Sets the value of the 'loadTimestamp' field.
      * @param value The value of 'loadTimestamp'.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder setLoadTimestamp(long value) {
      validate(fields()[4], value);
      this.loadTimestamp = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'loadTimestamp' field has been set.
      * @return True if the 'loadTimestamp' field has been set, false otherwise.
      */
    public boolean hasLoadTimestamp() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'loadTimestamp' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder clearLoadTimestamp() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'stationCapacity' field.
      * @return The value.
      */
    public int getStationCapacity() {
      return stationCapacity;
    }


    /**
      * Sets the value of the 'stationCapacity' field.
      * @param value The value of 'stationCapacity'.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder setStationCapacity(int value) {
      validate(fields()[5], value);
      this.stationCapacity = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'stationCapacity' field has been set.
      * @return True if the 'stationCapacity' field has been set, false otherwise.
      */
    public boolean hasStationCapacity() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'stationCapacity' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder clearStationCapacity() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'stationName' field.
      * @return The value.
      */
    public java.lang.String getStationName() {
      return stationName;
    }


    /**
      * Sets the value of the 'stationName' field.
      * @param value The value of 'stationName'.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder setStationName(java.lang.String value) {
      validate(fields()[6], value);
      this.stationName = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'stationName' field has been set.
      * @return True if the 'stationName' field has been set, false otherwise.
      */
    public boolean hasStationName() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'stationName' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder clearStationName() {
      stationName = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'isRenting' field.
      * @return The value.
      */
    public boolean getIsRenting() {
      return isRenting;
    }


    /**
      * Sets the value of the 'isRenting' field.
      * @param value The value of 'isRenting'.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder setIsRenting(boolean value) {
      validate(fields()[7], value);
      this.isRenting = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'isRenting' field has been set.
      * @return True if the 'isRenting' field has been set, false otherwise.
      */
    public boolean hasIsRenting() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'isRenting' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder clearIsRenting() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'isReturning' field.
      * @return The value.
      */
    public boolean getIsReturning() {
      return isReturning;
    }


    /**
      * Sets the value of the 'isReturning' field.
      * @param value The value of 'isReturning'.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder setIsReturning(boolean value) {
      validate(fields()[8], value);
      this.isReturning = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'isReturning' field has been set.
      * @return True if the 'isReturning' field has been set, false otherwise.
      */
    public boolean hasIsReturning() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'isReturning' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder clearIsReturning() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'isInstalled' field.
      * @return The value.
      */
    public boolean getIsInstalled() {
      return isInstalled;
    }


    /**
      * Sets the value of the 'isInstalled' field.
      * @param value The value of 'isInstalled'.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder setIsInstalled(boolean value) {
      validate(fields()[9], value);
      this.isInstalled = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'isInstalled' field has been set.
      * @return True if the 'isInstalled' field has been set, false otherwise.
      */
    public boolean hasIsInstalled() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'isInstalled' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder clearIsInstalled() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * @return The value.
      */
    public double getLatitude() {
      return latitude;
    }


    /**
      * Sets the value of the 'latitude' field.
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder setLatitude(double value) {
      validate(fields()[10], value);
      this.latitude = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'latitude' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder clearLatitude() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * @return The value.
      */
    public double getLongitude() {
      return longitude;
    }


    /**
      * Sets the value of the 'longitude' field.
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder setLongitude(double value) {
      validate(fields()[11], value);
      this.longitude = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'longitude' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroStationAvailability.Builder clearLongitude() {
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroStationAvailability build() {
      try {
        AvroStationAvailability record = new AvroStationAvailability();
        record.stationCode = fieldSetFlags()[0] ? this.stationCode : (java.lang.String) defaultValue(fields()[0]);
        record.mechanicalBikesAtStation = fieldSetFlags()[1] ? this.mechanicalBikesAtStation : (java.lang.Integer) defaultValue(fields()[1]);
        record.electricBikesAtStation = fieldSetFlags()[2] ? this.electricBikesAtStation : (java.lang.Integer) defaultValue(fields()[2]);
        record.availabilityTimestamp = fieldSetFlags()[3] ? this.availabilityTimestamp : (java.lang.Long) defaultValue(fields()[3]);
        record.loadTimestamp = fieldSetFlags()[4] ? this.loadTimestamp : (java.lang.Long) defaultValue(fields()[4]);
        record.stationCapacity = fieldSetFlags()[5] ? this.stationCapacity : (java.lang.Integer) defaultValue(fields()[5]);
        record.stationName = fieldSetFlags()[6] ? this.stationName : (java.lang.String) defaultValue(fields()[6]);
        record.isRenting = fieldSetFlags()[7] ? this.isRenting : (java.lang.Boolean) defaultValue(fields()[7]);
        record.isReturning = fieldSetFlags()[8] ? this.isReturning : (java.lang.Boolean) defaultValue(fields()[8]);
        record.isInstalled = fieldSetFlags()[9] ? this.isInstalled : (java.lang.Boolean) defaultValue(fields()[9]);
        record.latitude = fieldSetFlags()[10] ? this.latitude : (java.lang.Double) defaultValue(fields()[10]);
        record.longitude = fieldSetFlags()[11] ? this.longitude : (java.lang.Double) defaultValue(fields()[11]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroStationAvailability>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroStationAvailability>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroStationAvailability>
    READER$ = (org.apache.avro.io.DatumReader<AvroStationAvailability>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.stationCode);

    out.writeInt(this.mechanicalBikesAtStation);

    out.writeInt(this.electricBikesAtStation);

    out.writeLong(this.availabilityTimestamp);

    out.writeLong(this.loadTimestamp);

    out.writeInt(this.stationCapacity);

    out.writeString(this.stationName);

    out.writeBoolean(this.isRenting);

    out.writeBoolean(this.isReturning);

    out.writeBoolean(this.isInstalled);

    out.writeDouble(this.latitude);

    out.writeDouble(this.longitude);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.stationCode = in.readString();

      this.mechanicalBikesAtStation = in.readInt();

      this.electricBikesAtStation = in.readInt();

      this.availabilityTimestamp = in.readLong();

      this.loadTimestamp = in.readLong();

      this.stationCapacity = in.readInt();

      this.stationName = in.readString();

      this.isRenting = in.readBoolean();

      this.isReturning = in.readBoolean();

      this.isInstalled = in.readBoolean();

      this.latitude = in.readDouble();

      this.longitude = in.readDouble();

    } else {
      for (int i = 0; i < 12; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.stationCode = in.readString();
          break;

        case 1:
          this.mechanicalBikesAtStation = in.readInt();
          break;

        case 2:
          this.electricBikesAtStation = in.readInt();
          break;

        case 3:
          this.availabilityTimestamp = in.readLong();
          break;

        case 4:
          this.loadTimestamp = in.readLong();
          break;

        case 5:
          this.stationCapacity = in.readInt();
          break;

        case 6:
          this.stationName = in.readString();
          break;

        case 7:
          this.isRenting = in.readBoolean();
          break;

        case 8:
          this.isReturning = in.readBoolean();
          break;

        case 9:
          this.isInstalled = in.readBoolean();
          break;

        case 10:
          this.latitude = in.readDouble();
          break;

        case 11:
          this.longitude = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










