/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package velibstreaming.avro.record.source;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroBicycleCounterCharacteristics extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2324910309407166212L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroBicycleCounterCharacteristics\",\"namespace\":\"velibstreaming.avro.record.source\",\"fields\":[{\"name\":\"counterId\",\"type\":\"string\"},{\"name\":\"latitude\",\"type\":\"double\"},{\"name\":\"longitude\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroBicycleCounterCharacteristics> ENCODER =
      new BinaryMessageEncoder<AvroBicycleCounterCharacteristics>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroBicycleCounterCharacteristics> DECODER =
      new BinaryMessageDecoder<AvroBicycleCounterCharacteristics>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroBicycleCounterCharacteristics> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroBicycleCounterCharacteristics> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroBicycleCounterCharacteristics> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroBicycleCounterCharacteristics>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroBicycleCounterCharacteristics to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroBicycleCounterCharacteristics from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroBicycleCounterCharacteristics instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroBicycleCounterCharacteristics fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence counterId;
  @Deprecated public double latitude;
  @Deprecated public double longitude;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroBicycleCounterCharacteristics() {}

  /**
   * All-args constructor.
   * @param counterId The new value for counterId
   * @param latitude The new value for latitude
   * @param longitude The new value for longitude
   */
  public AvroBicycleCounterCharacteristics(java.lang.CharSequence counterId, java.lang.Double latitude, java.lang.Double longitude) {
    this.counterId = counterId;
    this.latitude = latitude;
    this.longitude = longitude;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return counterId;
    case 1: return latitude;
    case 2: return longitude;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: counterId = (java.lang.CharSequence)value$; break;
    case 1: latitude = (java.lang.Double)value$; break;
    case 2: longitude = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'counterId' field.
   * @return The value of the 'counterId' field.
   */
  public java.lang.CharSequence getCounterId() {
    return counterId;
  }


  /**
   * Sets the value of the 'counterId' field.
   * @param value the value to set.
   */
  public void setCounterId(java.lang.CharSequence value) {
    this.counterId = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return The value of the 'latitude' field.
   */
  public double getLatitude() {
    return latitude;
  }


  /**
   * Sets the value of the 'latitude' field.
   * @param value the value to set.
   */
  public void setLatitude(double value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return The value of the 'longitude' field.
   */
  public double getLongitude() {
    return longitude;
  }


  /**
   * Sets the value of the 'longitude' field.
   * @param value the value to set.
   */
  public void setLongitude(double value) {
    this.longitude = value;
  }

  /**
   * Creates a new AvroBicycleCounterCharacteristics RecordBuilder.
   * @return A new AvroBicycleCounterCharacteristics RecordBuilder
   */
  public static velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics.Builder newBuilder() {
    return new velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics.Builder();
  }

  /**
   * Creates a new AvroBicycleCounterCharacteristics RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroBicycleCounterCharacteristics RecordBuilder
   */
  public static velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics.Builder newBuilder(velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics.Builder other) {
    if (other == null) {
      return new velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics.Builder();
    } else {
      return new velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics.Builder(other);
    }
  }

  /**
   * Creates a new AvroBicycleCounterCharacteristics RecordBuilder by copying an existing AvroBicycleCounterCharacteristics instance.
   * @param other The existing instance to copy.
   * @return A new AvroBicycleCounterCharacteristics RecordBuilder
   */
  public static velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics.Builder newBuilder(velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics other) {
    if (other == null) {
      return new velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics.Builder();
    } else {
      return new velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroBicycleCounterCharacteristics instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroBicycleCounterCharacteristics>
    implements org.apache.avro.data.RecordBuilder<AvroBicycleCounterCharacteristics> {

    private java.lang.CharSequence counterId;
    private double latitude;
    private double longitude;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.counterId)) {
        this.counterId = data().deepCopy(fields()[0].schema(), other.counterId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.latitude)) {
        this.latitude = data().deepCopy(fields()[1].schema(), other.latitude);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.longitude)) {
        this.longitude = data().deepCopy(fields()[2].schema(), other.longitude);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroBicycleCounterCharacteristics instance
     * @param other The existing instance to copy.
     */
    private Builder(velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.counterId)) {
        this.counterId = data().deepCopy(fields()[0].schema(), other.counterId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.latitude)) {
        this.latitude = data().deepCopy(fields()[1].schema(), other.latitude);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.longitude)) {
        this.longitude = data().deepCopy(fields()[2].schema(), other.longitude);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'counterId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCounterId() {
      return counterId;
    }


    /**
      * Sets the value of the 'counterId' field.
      * @param value The value of 'counterId'.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics.Builder setCounterId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.counterId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'counterId' field has been set.
      * @return True if the 'counterId' field has been set, false otherwise.
      */
    public boolean hasCounterId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'counterId' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics.Builder clearCounterId() {
      counterId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * @return The value.
      */
    public double getLatitude() {
      return latitude;
    }


    /**
      * Sets the value of the 'latitude' field.
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics.Builder setLatitude(double value) {
      validate(fields()[1], value);
      this.latitude = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'latitude' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics.Builder clearLatitude() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * @return The value.
      */
    public double getLongitude() {
      return longitude;
    }


    /**
      * Sets the value of the 'longitude' field.
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics.Builder setLongitude(double value) {
      validate(fields()[2], value);
      this.longitude = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'longitude' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.source.AvroBicycleCounterCharacteristics.Builder clearLongitude() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroBicycleCounterCharacteristics build() {
      try {
        AvroBicycleCounterCharacteristics record = new AvroBicycleCounterCharacteristics();
        record.counterId = fieldSetFlags()[0] ? this.counterId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.latitude = fieldSetFlags()[1] ? this.latitude : (java.lang.Double) defaultValue(fields()[1]);
        record.longitude = fieldSetFlags()[2] ? this.longitude : (java.lang.Double) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroBicycleCounterCharacteristics>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroBicycleCounterCharacteristics>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroBicycleCounterCharacteristics>
    READER$ = (org.apache.avro.io.DatumReader<AvroBicycleCounterCharacteristics>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.counterId);

    out.writeDouble(this.latitude);

    out.writeDouble(this.longitude);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.counterId = in.readString(this.counterId instanceof Utf8 ? (Utf8)this.counterId : null);

      this.latitude = in.readDouble();

      this.longitude = in.readDouble();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.counterId = in.readString(this.counterId instanceof Utf8 ? (Utf8)this.counterId : null);
          break;

        case 1:
          this.latitude = in.readDouble();
          break;

        case 2:
          this.longitude = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










