/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package velibstreaming.avro.record;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AvroRoadWork extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7503001370527920071L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroRoadWork\",\"namespace\":\"velibstreaming.avro.record\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"object\",\"type\":[\"null\",\"string\"]},{\"name\":\"impactDetails\",\"type\":[\"null\",\"string\"]},{\"name\":\"perturbationLevel\",\"type\":{\"type\":\"enum\",\"name\":\"PerturbationLevel\",\"symbols\":[\"VERY_DISTURBING\",\"DISTURBING\",\"NONE\"]}},{\"name\":\"streetName\",\"type\":[\"null\",\"string\"]},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"Status\",\"symbols\":[\"TO_COME\",\"ONGOING\",\"HALTED\",\"EXTENDED\",\"FINISHED\",\"NONE\"]}},{\"name\":\"startTimestamp\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"endTimestamp\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"latitude\",\"type\":\"double\"},{\"name\":\"longitude\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroRoadWork> ENCODER =
      new BinaryMessageEncoder<AvroRoadWork>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroRoadWork> DECODER =
      new BinaryMessageDecoder<AvroRoadWork>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroRoadWork> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroRoadWork> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroRoadWork> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroRoadWork>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroRoadWork to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroRoadWork from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroRoadWork instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroRoadWork fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence object;
  @Deprecated public java.lang.CharSequence impactDetails;
  @Deprecated public velibstreaming.avro.record.PerturbationLevel perturbationLevel;
  @Deprecated public java.lang.CharSequence streetName;
  @Deprecated public velibstreaming.avro.record.Status status;
  @Deprecated public long startTimestamp;
  @Deprecated public long endTimestamp;
  @Deprecated public double latitude;
  @Deprecated public double longitude;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroRoadWork() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param object The new value for object
   * @param impactDetails The new value for impactDetails
   * @param perturbationLevel The new value for perturbationLevel
   * @param streetName The new value for streetName
   * @param status The new value for status
   * @param startTimestamp The new value for startTimestamp
   * @param endTimestamp The new value for endTimestamp
   * @param latitude The new value for latitude
   * @param longitude The new value for longitude
   */
  public AvroRoadWork(java.lang.CharSequence id, java.lang.CharSequence object, java.lang.CharSequence impactDetails, velibstreaming.avro.record.PerturbationLevel perturbationLevel, java.lang.CharSequence streetName, velibstreaming.avro.record.Status status, java.lang.Long startTimestamp, java.lang.Long endTimestamp, java.lang.Double latitude, java.lang.Double longitude) {
    this.id = id;
    this.object = object;
    this.impactDetails = impactDetails;
    this.perturbationLevel = perturbationLevel;
    this.streetName = streetName;
    this.status = status;
    this.startTimestamp = startTimestamp;
    this.endTimestamp = endTimestamp;
    this.latitude = latitude;
    this.longitude = longitude;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return object;
    case 2: return impactDetails;
    case 3: return perturbationLevel;
    case 4: return streetName;
    case 5: return status;
    case 6: return startTimestamp;
    case 7: return endTimestamp;
    case 8: return latitude;
    case 9: return longitude;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: object = (java.lang.CharSequence)value$; break;
    case 2: impactDetails = (java.lang.CharSequence)value$; break;
    case 3: perturbationLevel = (velibstreaming.avro.record.PerturbationLevel)value$; break;
    case 4: streetName = (java.lang.CharSequence)value$; break;
    case 5: status = (velibstreaming.avro.record.Status)value$; break;
    case 6: startTimestamp = (java.lang.Long)value$; break;
    case 7: endTimestamp = (java.lang.Long)value$; break;
    case 8: latitude = (java.lang.Double)value$; break;
    case 9: longitude = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'object' field.
   * @return The value of the 'object' field.
   */
  public java.lang.CharSequence getObject() {
    return object;
  }


  /**
   * Sets the value of the 'object' field.
   * @param value the value to set.
   */
  public void setObject(java.lang.CharSequence value) {
    this.object = value;
  }

  /**
   * Gets the value of the 'impactDetails' field.
   * @return The value of the 'impactDetails' field.
   */
  public java.lang.CharSequence getImpactDetails() {
    return impactDetails;
  }


  /**
   * Sets the value of the 'impactDetails' field.
   * @param value the value to set.
   */
  public void setImpactDetails(java.lang.CharSequence value) {
    this.impactDetails = value;
  }

  /**
   * Gets the value of the 'perturbationLevel' field.
   * @return The value of the 'perturbationLevel' field.
   */
  public velibstreaming.avro.record.PerturbationLevel getPerturbationLevel() {
    return perturbationLevel;
  }


  /**
   * Sets the value of the 'perturbationLevel' field.
   * @param value the value to set.
   */
  public void setPerturbationLevel(velibstreaming.avro.record.PerturbationLevel value) {
    this.perturbationLevel = value;
  }

  /**
   * Gets the value of the 'streetName' field.
   * @return The value of the 'streetName' field.
   */
  public java.lang.CharSequence getStreetName() {
    return streetName;
  }


  /**
   * Sets the value of the 'streetName' field.
   * @param value the value to set.
   */
  public void setStreetName(java.lang.CharSequence value) {
    this.streetName = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public velibstreaming.avro.record.Status getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(velibstreaming.avro.record.Status value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'startTimestamp' field.
   * @return The value of the 'startTimestamp' field.
   */
  public long getStartTimestamp() {
    return startTimestamp;
  }


  /**
   * Sets the value of the 'startTimestamp' field.
   * @param value the value to set.
   */
  public void setStartTimestamp(long value) {
    this.startTimestamp = value;
  }

  /**
   * Gets the value of the 'endTimestamp' field.
   * @return The value of the 'endTimestamp' field.
   */
  public long getEndTimestamp() {
    return endTimestamp;
  }


  /**
   * Sets the value of the 'endTimestamp' field.
   * @param value the value to set.
   */
  public void setEndTimestamp(long value) {
    this.endTimestamp = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return The value of the 'latitude' field.
   */
  public double getLatitude() {
    return latitude;
  }


  /**
   * Sets the value of the 'latitude' field.
   * @param value the value to set.
   */
  public void setLatitude(double value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return The value of the 'longitude' field.
   */
  public double getLongitude() {
    return longitude;
  }


  /**
   * Sets the value of the 'longitude' field.
   * @param value the value to set.
   */
  public void setLongitude(double value) {
    this.longitude = value;
  }

  /**
   * Creates a new AvroRoadWork RecordBuilder.
   * @return A new AvroRoadWork RecordBuilder
   */
  public static velibstreaming.avro.record.AvroRoadWork.Builder newBuilder() {
    return new velibstreaming.avro.record.AvroRoadWork.Builder();
  }

  /**
   * Creates a new AvroRoadWork RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroRoadWork RecordBuilder
   */
  public static velibstreaming.avro.record.AvroRoadWork.Builder newBuilder(velibstreaming.avro.record.AvroRoadWork.Builder other) {
    if (other == null) {
      return new velibstreaming.avro.record.AvroRoadWork.Builder();
    } else {
      return new velibstreaming.avro.record.AvroRoadWork.Builder(other);
    }
  }

  /**
   * Creates a new AvroRoadWork RecordBuilder by copying an existing AvroRoadWork instance.
   * @param other The existing instance to copy.
   * @return A new AvroRoadWork RecordBuilder
   */
  public static velibstreaming.avro.record.AvroRoadWork.Builder newBuilder(velibstreaming.avro.record.AvroRoadWork other) {
    if (other == null) {
      return new velibstreaming.avro.record.AvroRoadWork.Builder();
    } else {
      return new velibstreaming.avro.record.AvroRoadWork.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroRoadWork instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroRoadWork>
    implements org.apache.avro.data.RecordBuilder<AvroRoadWork> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence object;
    private java.lang.CharSequence impactDetails;
    private velibstreaming.avro.record.PerturbationLevel perturbationLevel;
    private java.lang.CharSequence streetName;
    private velibstreaming.avro.record.Status status;
    private long startTimestamp;
    private long endTimestamp;
    private double latitude;
    private double longitude;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(velibstreaming.avro.record.AvroRoadWork.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.object)) {
        this.object = data().deepCopy(fields()[1].schema(), other.object);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.impactDetails)) {
        this.impactDetails = data().deepCopy(fields()[2].schema(), other.impactDetails);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.perturbationLevel)) {
        this.perturbationLevel = data().deepCopy(fields()[3].schema(), other.perturbationLevel);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.streetName)) {
        this.streetName = data().deepCopy(fields()[4].schema(), other.streetName);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.startTimestamp)) {
        this.startTimestamp = data().deepCopy(fields()[6].schema(), other.startTimestamp);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.endTimestamp)) {
        this.endTimestamp = data().deepCopy(fields()[7].schema(), other.endTimestamp);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.latitude)) {
        this.latitude = data().deepCopy(fields()[8].schema(), other.latitude);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.longitude)) {
        this.longitude = data().deepCopy(fields()[9].schema(), other.longitude);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroRoadWork instance
     * @param other The existing instance to copy.
     */
    private Builder(velibstreaming.avro.record.AvroRoadWork other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.object)) {
        this.object = data().deepCopy(fields()[1].schema(), other.object);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.impactDetails)) {
        this.impactDetails = data().deepCopy(fields()[2].schema(), other.impactDetails);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.perturbationLevel)) {
        this.perturbationLevel = data().deepCopy(fields()[3].schema(), other.perturbationLevel);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.streetName)) {
        this.streetName = data().deepCopy(fields()[4].schema(), other.streetName);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.startTimestamp)) {
        this.startTimestamp = data().deepCopy(fields()[6].schema(), other.startTimestamp);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.endTimestamp)) {
        this.endTimestamp = data().deepCopy(fields()[7].schema(), other.endTimestamp);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.latitude)) {
        this.latitude = data().deepCopy(fields()[8].schema(), other.latitude);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.longitude)) {
        this.longitude = data().deepCopy(fields()[9].schema(), other.longitude);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'object' field.
      * @return The value.
      */
    public java.lang.CharSequence getObject() {
      return object;
    }


    /**
      * Sets the value of the 'object' field.
      * @param value The value of 'object'.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder setObject(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.object = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'object' field has been set.
      * @return True if the 'object' field has been set, false otherwise.
      */
    public boolean hasObject() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'object' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder clearObject() {
      object = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'impactDetails' field.
      * @return The value.
      */
    public java.lang.CharSequence getImpactDetails() {
      return impactDetails;
    }


    /**
      * Sets the value of the 'impactDetails' field.
      * @param value The value of 'impactDetails'.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder setImpactDetails(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.impactDetails = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'impactDetails' field has been set.
      * @return True if the 'impactDetails' field has been set, false otherwise.
      */
    public boolean hasImpactDetails() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'impactDetails' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder clearImpactDetails() {
      impactDetails = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'perturbationLevel' field.
      * @return The value.
      */
    public velibstreaming.avro.record.PerturbationLevel getPerturbationLevel() {
      return perturbationLevel;
    }


    /**
      * Sets the value of the 'perturbationLevel' field.
      * @param value The value of 'perturbationLevel'.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder setPerturbationLevel(velibstreaming.avro.record.PerturbationLevel value) {
      validate(fields()[3], value);
      this.perturbationLevel = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'perturbationLevel' field has been set.
      * @return True if the 'perturbationLevel' field has been set, false otherwise.
      */
    public boolean hasPerturbationLevel() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'perturbationLevel' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder clearPerturbationLevel() {
      perturbationLevel = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'streetName' field.
      * @return The value.
      */
    public java.lang.CharSequence getStreetName() {
      return streetName;
    }


    /**
      * Sets the value of the 'streetName' field.
      * @param value The value of 'streetName'.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder setStreetName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.streetName = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'streetName' field has been set.
      * @return True if the 'streetName' field has been set, false otherwise.
      */
    public boolean hasStreetName() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'streetName' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder clearStreetName() {
      streetName = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public velibstreaming.avro.record.Status getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder setStatus(velibstreaming.avro.record.Status value) {
      validate(fields()[5], value);
      this.status = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder clearStatus() {
      status = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'startTimestamp' field.
      * @return The value.
      */
    public long getStartTimestamp() {
      return startTimestamp;
    }


    /**
      * Sets the value of the 'startTimestamp' field.
      * @param value The value of 'startTimestamp'.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder setStartTimestamp(long value) {
      validate(fields()[6], value);
      this.startTimestamp = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'startTimestamp' field has been set.
      * @return True if the 'startTimestamp' field has been set, false otherwise.
      */
    public boolean hasStartTimestamp() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'startTimestamp' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder clearStartTimestamp() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'endTimestamp' field.
      * @return The value.
      */
    public long getEndTimestamp() {
      return endTimestamp;
    }


    /**
      * Sets the value of the 'endTimestamp' field.
      * @param value The value of 'endTimestamp'.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder setEndTimestamp(long value) {
      validate(fields()[7], value);
      this.endTimestamp = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'endTimestamp' field has been set.
      * @return True if the 'endTimestamp' field has been set, false otherwise.
      */
    public boolean hasEndTimestamp() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'endTimestamp' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder clearEndTimestamp() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * @return The value.
      */
    public double getLatitude() {
      return latitude;
    }


    /**
      * Sets the value of the 'latitude' field.
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder setLatitude(double value) {
      validate(fields()[8], value);
      this.latitude = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'latitude' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder clearLatitude() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * @return The value.
      */
    public double getLongitude() {
      return longitude;
    }


    /**
      * Sets the value of the 'longitude' field.
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder setLongitude(double value) {
      validate(fields()[9], value);
      this.longitude = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'longitude' field.
      * @return This builder.
      */
    public velibstreaming.avro.record.AvroRoadWork.Builder clearLongitude() {
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroRoadWork build() {
      try {
        AvroRoadWork record = new AvroRoadWork();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.object = fieldSetFlags()[1] ? this.object : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.impactDetails = fieldSetFlags()[2] ? this.impactDetails : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.perturbationLevel = fieldSetFlags()[3] ? this.perturbationLevel : (velibstreaming.avro.record.PerturbationLevel) defaultValue(fields()[3]);
        record.streetName = fieldSetFlags()[4] ? this.streetName : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.status = fieldSetFlags()[5] ? this.status : (velibstreaming.avro.record.Status) defaultValue(fields()[5]);
        record.startTimestamp = fieldSetFlags()[6] ? this.startTimestamp : (java.lang.Long) defaultValue(fields()[6]);
        record.endTimestamp = fieldSetFlags()[7] ? this.endTimestamp : (java.lang.Long) defaultValue(fields()[7]);
        record.latitude = fieldSetFlags()[8] ? this.latitude : (java.lang.Double) defaultValue(fields()[8]);
        record.longitude = fieldSetFlags()[9] ? this.longitude : (java.lang.Double) defaultValue(fields()[9]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroRoadWork>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroRoadWork>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroRoadWork>
    READER$ = (org.apache.avro.io.DatumReader<AvroRoadWork>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    if (this.object == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.object);
    }

    if (this.impactDetails == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.impactDetails);
    }

    out.writeEnum(this.perturbationLevel.ordinal());

    if (this.streetName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.streetName);
    }

    out.writeEnum(this.status.ordinal());

    out.writeLong(this.startTimestamp);

    out.writeLong(this.endTimestamp);

    out.writeDouble(this.latitude);

    out.writeDouble(this.longitude);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.object = null;
      } else {
        this.object = in.readString(this.object instanceof Utf8 ? (Utf8)this.object : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.impactDetails = null;
      } else {
        this.impactDetails = in.readString(this.impactDetails instanceof Utf8 ? (Utf8)this.impactDetails : null);
      }

      this.perturbationLevel = velibstreaming.avro.record.PerturbationLevel.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.streetName = null;
      } else {
        this.streetName = in.readString(this.streetName instanceof Utf8 ? (Utf8)this.streetName : null);
      }

      this.status = velibstreaming.avro.record.Status.values()[in.readEnum()];

      this.startTimestamp = in.readLong();

      this.endTimestamp = in.readLong();

      this.latitude = in.readDouble();

      this.longitude = in.readDouble();

    } else {
      for (int i = 0; i < 10; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.object = null;
          } else {
            this.object = in.readString(this.object instanceof Utf8 ? (Utf8)this.object : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.impactDetails = null;
          } else {
            this.impactDetails = in.readString(this.impactDetails instanceof Utf8 ? (Utf8)this.impactDetails : null);
          }
          break;

        case 3:
          this.perturbationLevel = velibstreaming.avro.record.PerturbationLevel.values()[in.readEnum()];
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.streetName = null;
          } else {
            this.streetName = in.readString(this.streetName instanceof Utf8 ? (Utf8)this.streetName : null);
          }
          break;

        case 5:
          this.status = velibstreaming.avro.record.Status.values()[in.readEnum()];
          break;

        case 6:
          this.startTimestamp = in.readLong();
          break;

        case 7:
          this.endTimestamp = in.readLong();
          break;

        case 8:
          this.latitude = in.readDouble();
          break;

        case 9:
          this.longitude = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










