@startuml
title
<b>High level topology</b>
(Kafka Stream)
end title

rectangle stationAvailabilityClient <<producer>>
rectangle stationAvailabilities <<topic>>
rectangle stationUpdates <<topic>>
rectangle hourlyStationStats<<topic>>
rectangle stationStatus <<topic>>
rectangle bikesLocked <<topic>>
database station_hourly_statistics <<database>>


stationAvailabilityClient --> stationAvailabilities 
stationAvailabilities --> stationUpdates : drop duplicates and compute diff
stationUpdates --> hourlyStationStats : aggregate on a 1-hour window
hourlyStationStats --> bikesLocked
hourlyStationStats -> station_hourly_statistics
stationUpdates --> stationStatus
station_hourly_statistics ..> stationStatus
station_hourly_statistics ..> bikesLocked

skinparam rectangle{
    backgroundColor<<topic>> Gainsboro
    backgroundColor<<table>> Gainsboro
    backgroundColor<<producer>> Coral
    backgroundColor<<consumer>> Coral
    borderColor<<topic>> transparent
    borderColor<<table>> transparent
    borderColor<<producer>> transparent
    borderColor<<consumer>> transparent
}

skinparam database{ 
   backgroundColor<<database>> Coral
   borderColor transparent
}

skinparam{
   ArrowColor DeepSkyBlue
   shadowing false
}
@enduml