@startuml
title
<b>High level topology</b>
(Kafka Stream)
end title


frame "Station status topology"{
   rectangle stationAvailabilityClient <<producer>>
   rectangle stationAvailabilities <<topic>>
   rectangle stationUpdates <<topic>>
   rectangle hourlyStationStats<<topic>>
   rectangle stationStatus <<topic>>
   rectangle bikesLocked <<topic>>
   database statisticsDb <<database>>
}

stationAvailabilityClient --> stationAvailabilities 
stationAvailabilities --> stationUpdates : deduplicated
stationUpdates --> hourlyStationStats : windowed
hourlyStationStats --> bikesLocked
hourlyStationStats -> statisticsDb
stationUpdates --> stationStatus
statisticsDb ..> stationStatus

frame "Nearby traffic topology"{
   rectangle bikeCountsClient <<producer>>
   rectangle bikeCounts <<topic>>
   rectangle bikeCountUpdates <<topic>>
   rectangle countUpdatesProjected<<topic>>
   rectangle zoneToStations<<table>>
   rectangle stationNearbyCounts <<topic>>
   rectangle hourlyStationNearbyTraffic <<topic>>
   database trafficDb <<database>>
}


bikeCountsClient --> bikeCounts 
bikeCounts --> bikeCountUpdates : deduplicated
stationUpdates --> zoneToStations
bikeCountUpdates --> countUpdatesProjected: projected on nearby zones
zoneToStations--> stationNearbyCounts 
countUpdatesProjected --> stationNearbyCounts 
stationNearbyCounts --> hourlyStationNearbyTraffic : windowed
hourlyStationNearbyTraffic --> trafficDb

skinparam rectangle{
    backgroundColor<<topic>> Gainsboro
    backgroundColor<<table>> Gainsboro
    backgroundColor<<producer>> Coral
    backgroundColor<<consumer>> Coral
    borderColor<<topic>> transparent
    borderColor<<table>> transparent
    borderColor<<producer>> transparent
    borderColor<<consumer>> transparent
}

skinparam database{ 
   backgroundColor<<database>> Coral
   borderColor transparent
}

skinparam{
   ArrowColor DeepSkyBlue
   ArrowFontColor Coral
   shadowing false
}
@enduml